#!/bin/sh

set -e

lb config noauto \
	--iso-application SuaveOS \
	--iso-volume SuaveOS \
	--archive-areas "main contrib non-free" \
	--firmware-chroot true \
	--system live \
	--bootappend-live "boot=live components username=suave user-fullname='suave' hostname=SuaveOS persistence" \
        --architecture amd64 \
        --distribution bullseye \
	"${@}"
